.macro bridge_gfx_data
    .byte $c3  ; 11....11
    .byte $c3  ; 11....11
    .byte $c3  ; 11....11
    .byte $c3  ; 11....11
    .byte $42  ; .1....1.
    .byte $42  ; .1....1.
    .byte $42  ; .1....1.
    .byte $42  ; .1....1.
    .byte $42  ; .1....1.
    .byte $42  ; .1....1.
    .byte $42  ; .1....1.
    .byte $42  ; .1....1.
    .byte $42  ; .1....1.
    .byte $42  ; .1....1.
    .byte $42  ; .1....1.
    .byte $42  ; .1....1.
    .byte $42  ; .1....1.
    .byte $42  ; .1....1.
    .byte $42  ; .1....1.
    .byte $42  ; .1....1.
    .byte $c3  ; 11....11
    .byte $c3  ; 11....11
    .byte $c3  ; 11....11
    .byte $c3  ; 11....11
    .byte 0
.endmacro