.macro port_gfxgr_data
    .byte $fe  ; 1111111.
    .byte $aa  ; 1.1.1.1.
    .byte $fe  ; 1111111.
    .byte $aa  ; 1.1.1.1.
    .byte $fe  ; 1111111.
    .byte $aa  ; 1.1.1.1.
    .byte $fe  ; 1111111.
    .byte $aa  ; 1.1.1.1.
    .byte $fe  ; 1111111.
    .byte $aa  ; 1.1.1.1.
    .byte $fe  ; 1111111.
    .byte $aa  ; 1.1.1.1.
    .byte $fe  ; 1111111.
    .byte $aa  ; 1.1.1.1.
    .byte $fe  ; 1111111.
    .byte $aa  ; 1.1.1.1.
    .byte 0
.endmacro
